import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import SideBar from '../src/components/SideBar';
import styles from '../styles/Home.module.css';
import React, { useState, useEffect } from 'react';
import Modules from '../src/components/Modules';

const Home: NextPage = () => {
    const [displayModule, setDisplayModule] = useState('default');

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.gridContainer}>
                <SideBar display={displayModule} setDisplay={setDisplayModule}></SideBar>
                <div className={styles.gridCol2}>
                    <Modules display={displayModule}></Modules>
                </div>
            </div>

            <footer className="footer footer-center p-4 bg-base-300 text-base-content">
                <div>
                    <p>Copyright © 2022 - All right reserved by Ethan Sabini</p>
                </div>
            </footer>
        </div >
    )
};

export default Home;
